---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Login to GitHub Container Registry
      ansible.builtin.shell:
        cmd: echo "{{ docker_password }}" | docker login "{{ docker_host }}" --username "{{ docker_username }}" --password-stdin
    - name: Execute Docker deployment
      ansible.builtin.include_role:
        name: ansible-docker-deployment
      vars:
        docker_deployment_project_name: '{{ project_name }}'
        docker_deployment_release_name: '{{ release_name }}'
        docker_deployment_release_files:
          - local: ../../c3nav.docker-compose.yml
            remote: docker-compose.yml
          - local: ../../.env
            remote: .env
          - local: ../../db/dump.sql
            remote: dump.sql
          - local: ../../data/
            remote: ./data/
            mode: '777'
            recurse: false
        
    - name: Load database dump
      ansible.builtin.shell:
        chdir: /var/docker/{{project_name}}/releases/{{release_name}}
        cmd: cat dump.sql | docker exec -i {{project_name}}-postgres-1 su - postgres -c 'psql c3nav'
    
    - name: Call post-migration scripts
      shell: docker exec -i -w /app {{project_name}}-c3nav-core-1 '/app/env/bin/python manage.py clearmapcache --include-history --include-geometries && /app/env/bin/python manage.py collectstatic -l --no-input'
